image: registry.nic.cz/turris/sentinel/containers/tests/debian-bullseye:latest

stages:
  - lint
  - test
  - publish

# The name of the repository must correspond to one defined in pyproject.toml
# Unfortunately there is no way how to pass credentials directly to install command
.poetry_config_download_auth: &poetry_config_download_auth
  - poetry config http-basic.sentinel-pkg-registry-download "${GITLAB_SENTINEL_PACKAGE_USERNAME}" "${GITLAB_SENTINEL_PACKAGE_TOKEN}"

.lint_common: &lint_common
  stage: lint
  needs: []
  before_script:
    - eval "$(pyenv init -)"
    # The name must correspond to one of the names from the image
    - pyenv activate py39
    - *poetry_config_download_auth
    - poetry install

format-check:
  <<: *lint_common
  script:
    - poetry run black --check .

imports-check:
  <<: *lint_common
  script:
    - poetry run isort --check .

lint-check:
  <<: *lint_common
  script:
    - poetry run flake8p .

type-check:
  <<: *lint_common
  script:
    - poetry run mypy .

test:
  stage: test
  needs: []
  parallel:
    matrix:
    # These names must correspond to names of the venvs from the image
      - VENV: ['py38', 'py39', 'py310', 'py311']
  script:
    - eval "$(pyenv init -)"
    - pyenv activate ${VENV}
    - *poetry_config_download_auth
    - poetry install --without=dev
    - poetry run pytest --junitxml=report.xml --cov-report=xml --cov-report=term --cov=turris_sentinel_template_box -v tests
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/^TOTAL.* (\d+)%$/'

publish:
  stage: publish
  needs: [format-check, imports-check, lint-check, type-check, test]
  script:
    # The repository name must correspond to the name of a repository from pyproject.toml
    - poetry publish --build --repository sentinel-pkg-registry-publish --username gitlab-ci-token --password $CI_JOB_TOKEN
  rules:
    # It publishes a package for tag created in any branch
    # There was no nice way to limit it on tags in master only
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+.[0-9]+.[0-9]+$/'
      when: on_success
    - when: never
